### ISSUE TITLE
 Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library

### ISSUE THREAD

**Issue by itxuye** [markzhai/DataBinding-RecyclerViewAdapter#2]
Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.github.markzhai:databinding-rv-adapter:1.0.0] D:\Android\Demo\GankDBinding\app\build\intermediates\exploded-aar\com.github.markzhai\databinding-rv-adapter\1.0.0\AndroidManifest.xml
>     Suggestion: use tools:overrideLibrary="com.github.markzhai.recyclerview" to force usage

So i should  solve it like this.
uses-sdk tools:overrideLibrary="com.github.markzhai.recyclerview"

QAQ.

**Comment by itxuye** [comment]
So i should  solve it like this.
<uses-sdk tools:overrideLibrary="com.github.markzhai.recyclerview"/>

**Comment by itxuye** [comment]
So i should  solve it like this.

Add <uses-sdk tools:overrideLibrary="com.github.markzhai.recyclerview"/>

**Comment by markzhai** [comment]
Sorry, I should downgrade its minSdkVersion

**Comment by itxuye** [comment]
@markzhai Thanks.
